### ISSUE TITLE
[FIX] 기초세팅 추가 및 수정사항 반영

### ISSUE THREAD

**Issue by MoonsuKang** [NOW-SOPT-APP5-KakaoPay/KakaoPay-Android#1]
## 💡 Issue
- 기초세팅에 부족한 부분이 있다는 것을 확인.
## 📝 todo

- [x] 바텀시트 베이스 클래스 추가
- [x] 각 베이스 클래스에 초기화 메서드 추가
- [x] Manifest에 테마 추가
